export { default as Table } from "./Table"
export { default as IconPhoto } from "./IconPhoto"
export { default as SideMenu } from "./SideMenu"
export { default as SideBar } from "./SideBar"
export { default as InputOption} from "./InputOption"
export { default as InputOptionPatient} from "./InputOptionPatient"
export { default as InputOptionUser} from "./InputOptionUser"
export { default as Input} from "./Input"
export { default as CalendarTime} from "./CalendarTime"
export { default as CardAppoinment} from "./CardAppoinment"
export { default as CustomChart} from "./Chart"

